export const actionTypes = {
  SAVE_ITEMCATE_SUCCESS: "SAVE_ITEMCATE_SUCCESS",
  FETCH_ITEMCATEGORY_SUCCESS: "FETCH_ITEMCATEGORY_SCUCESS",
  DELETE_ITEMCATEGORY_SUCCESS: "DELETE_ITEMCATEGORY_SCUCESS",
  SAVE_ITEMUNIT_SUCCESS: "SAVE_ITEMUNIT_SUCCESS",
  FETCH_ITEM_UNIT_SUCCESS: "FETCH_ITEM_UNIT_SUCCESS",
  DELETE_ITEM_UNIT_SUCCESS: "DELETE_ITEM_UNIT_SUCCESS",
  SAVE_CONTACT_SUCCESS: "SAVE_CONTACT_SUCCESS",
  FETCH_CONTACT_SUCCESS: "FETCH_CONTACT_SUCCESS",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  SAVE_ITEM_SUCCESS: "SAVE_ITEM_SUCCESS",
  FETCH_ITEM_SUCCESS: "FETCH_ITEM_SUCCESS",
  DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS"
};
