export const actionTypes = {
  CATEGORY: {
    CREATE: "CREATE_CATEGORY",
    FETCH_LIST: "FETCH_LIST_CATEGORY",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_CATEGORY",
    FETCH: "FETCH_CATEGORY",
    DELETE: "DELETE_CATEGORY",
    UPDATE: "UPDATE_CATEGORY",
    RESET: "RESET_CATEGORY"
  },
  UNIT: {
    CREATE: "CREATE_UNIT",
    FETCH_LIST: "FETCH_LIST_UNIT",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_UNIT",
    FETCH: "FETCH_UNIT",
    DELETE: "DELETE_UNIT",
    UPDATE: "UPDATE_UNIT",
    RESET: "RESET_UNIT"
  },
  CONTACT: {
    CREATE: "CREATE_CONTACT",
    FETCH_LIST: "FETCH_LIST_CONTACT",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_CONTACT",
    FETCH: "FETCH_CONTACT",
    DELETE: "DELETE_CONTACT",
    UPDATE: "UPDATE_CONTACT",
    RESET: "RESET_CONTACT"
  },
  ITEM: {
    CREATE: "CREATE_ITEM",
    FETCH_LIST: "FETCH_LIST_ITEM",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_ITEM",
    FETCH: "FETCH_ITEM",
    DELETE: "DELETE_ITEM",
    UPDATE: "UPDATE_ITEM",
    RESET: "RESET_ITEM"
  },
  REQUEST: {
    CREATE: "CREATE_REQUEST",
    FETCH_LIST: "FETCH_LIST_REQUEST",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_REQUEST",
    FETCH: "FETCH_REQUEST",
    DELETE: "DELETE_REQUEST",
    UPDATE: "UPDATE_REQUEST",
    RESET: "RESET_REQUEST"
  },
  PO: {
    CREATE: "CREATE_PO",
    FETCH_LIST: "FETCH_LIST_PO",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_PO",
    FETCH: "FETCH_PO",
    DELETE: "DELETE_PO",
    UPDATE: "UPDATE_PO",
    RESET: "RESET_PO"
  },
  RS: {
    CREATE: "CREATE_RS",
    FETCH_LIST: "FETCH_LIST_RS",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_RS",
    FETCH: "FETCH_RS",
    DELETE: "DELETE_RS",
    UPDATE: "UPDATE_RS",
    RESET: "RESET_RS"
  },
  DN: {
    CREATE: "CREATE_DN",
    FETCH_LIST: "FETCH_LIST_DN",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_DN",
    FETCH: "FETCH_DN",
    DELETE: "DELETE_DN",
    UPDATE: "UPDATE_DN",
    RESET: "RESET_DN"
  },
  RN: {
    CREATE: "CREATE_RN",
    FETCH_LIST: "FETCH_LIST_RN",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_RN",
    FETCH: "FETCH_RN",
    DELETE: "DELETE_RN",
    UPDATE: "UPDATE_RN",
    RESET: "RESET_RN"
  },
  REPORT: {
    EXPIRE_ITEM: "EXPIRE_ITEM_REPORT",
    RESET: "RESET_REPORT"
  }
};
