export const actionTypes = {
  CATEGORY: {
    CREATE: "CREATE_CATEGORY",
    FETCH_LIST: "FETCH_LIST_CATEGORY",
    FETCH_LIST_ALL: "FETCH_LIST_ALL_CATEGORY",
    FETCH: "FETCH_CATEGORY",
    DELETE: "DELETE_CATEGORY",
    UPDATE: "UPDATE_CATEGORY",
    RESET: "RESET_CATEGORY"
  },
  UNIT: {
    CREATE: "CREATE_UNIT",
    FETCH_LIST: "FETCH_LIST_UNIT",
    FETCH: "FETCH_UNIT",
    DELETE: "DELETE_UNIT",
    UPDATE: "UPDATE_UNIT",
    RESET: "RESET_UNIT"
  },
  CONTACT: {
    CREATE: "CREATE_CONTACT",
    FETCH_LIST: "FETCH_LIST_CONTACT",
    FETCH: "FETCH_CONTACT",
    DELETE: "DELETE_CONTACT",
    UPDATE: "UPDATE_CONTACT",
    RESET: "RESET_CONTACT"
  },
  ITEM: {
    CREATE: "CREATE_ITEM",
    FETCH_LIST: "FETCH_LIST_ITEM",
    FETCH: "FETCH_ITEM",
    DELETE: "DELETE_ITEM",
    UPDATE: "UPDATE_ITEM",
    RESET: "RESET_ITEM"
  }
};
